name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Run Black
      run: black --check .
    - name: Run Ruff
      run: ruff check .
    - name: Run Pyright
      uses: jakebailey/pyright-action@v1
      with:
        version: 1.1.378
